### PR TITLE
feat: axiom xor

### PR DESCRIPTION
**Pull request by RajeshRk18**
# Description

Added `xor`constraint for axiom backend
## Problem\*

Resolves 

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by Ethan-000 — APPROVED** [review]
Thanks!! This is good for now but I think in the latest halo2 release by axiom `xor` is added so we should be able to use that directly as well if the version of the dependency is updated https://github.com/axiom-crypto/halo2-lib/blob/400122a6cf074783d0e5ee904a711e75ddfff3d4/halo2-base/src/gates/flex_gate/mod.rs#L569

**Comment by RajeshRk18** [comment]
> Thanks!! This is good for now but I think in the latest halo2 release by axiom `xor` is added so we should be able to use that directly as well if the version of the dependency is updated https://github.com/axiom-crypto/halo2-lib/blob/400122a6cf074783d0e5ee904a711e75ddfff3d4/halo2-base/src/gates/flex_gate/mod.rs#L569

I'll change then!

**Comment by RajeshRk18** [comment]
In the latest [version](https://github.com/axiom-crypto/halo2-lib/blob/8cdbf542a70455042ff7c8cdbedb552ca174a00d/halo2-base/src/lib.rs#L178), `Context::new()` requires more arguments such as `type_id`, `context_id` and `copy_manager`. How can we do this across places where we instantiate `Context`?

**Comment by Ethan-000** [comment]
don't know much about how the new `Context` work :'(    Im ok with merging this as it is. may be the migration to new versions can happen in another PR

**Pull request merged**
